Fix to prevent the status interval from creeping up by 1-2 msec over time
axboe/fio pull request #1114
Opened 2020-11-02 16:57 UTC by jeffreyalien

With the current FIO version, we're seeing the status interval increase by 1 msec over time.  See an example in the stat-int-creep attached file.
[stat-int-creep.txt](https://github.com/axboe/fio/files/5476571/stat-int-creep.txt)

This issue will cause dip ( low ) in IOPS and BW plot vs time because parsing/plot tool can't get correct sum total IOPS and BW from multiple jobs when there is 1-2us increment in timestamp.

The issue was introduced in version 3.18 with the following commit - https://github.com/axboe/fio/commit/31eca641ad91634e5ffcf369cd756b0506a700c1 .   
And this commit made it slightly better - https://github.com/axboe/fio/commit/0f77d30d90b809fbf233b9474cc5d17c6bf73541
But the problem still exists.

The patch below is my attempt to correct the problem.  I'm not real familiar with the FIO code so I'm sure there could be better ways to do this.  Please review and provide any input that would make this fix better.

2020-11-04 08:18 UTC, sitsofe commented
Superficial feedback:
- Could you a prefix the area on your commit titles (see https://github.com/axboe/fio/pull/1050#issuecomment-663606909 )?
- Maybe shorten the title a touch (`prevent the status interval from creeping up`)
- Can you squash the fix into the original commit
- Add the excellent [description you've got in your first comment here](https://github.com/axboe/fio/pull/1114#issue-514193995) to your commit message
- Please add your Signed-off-by

2020-11-04 08:20 UTC, sitsofe requested changes
Does this supercede #982

2020-11-05 13:40 UTC, jeffreyalien commented
Sitsofe, This is not intended to supersede #982 but it seems like they may need to go together though.   
I will update the PR with the changes you suggested above.

2020-11-05 20:41 UTC, jeffreyalien commented
Replaced with PR #1119

2020-11-05 20:41 UTC, closed without merging

2020-11-05 20:41 UTC, jeffreyalien commented
Replaced with PR #1119.