engine/rados: Remove mandatory creation
axboe/fio pull request #1181
Opened 2021-02-08 13:49 UTC by aclamk

Changed connection procedure so it no longer attempts to create objects.
This change will affect tests that read objects without creating them first.

Signed-off-by: Adam Kupczyk <akupczyk@redhat.com>

2021-02-08 13:52 UTC, aclamk commented
The problem with current implementation is that touching (writing 0 bytes) to each object takes a lot of time, and also messes with ceph caches, inducing huge errors to tests related to cache performance.

2021-02-08 14:50 UTC, ifed01 approved these changes
LGTM

2021-02-08 20:40 UTC, sitsofe commented
I'd have to think about this but at a minimum could this be turned into an option?

2021-02-12 13:54 UTC, aclamk commented
@sitsofe I think that I synchronized rados engine with others.
I do not see codes in other engines that create files on init/setup.

2021-02-14 20:13 UTC, sitsofe commented
@aclamk The problem is going to be the change in behaviour. Technically some other ioengines may have creation done "for free" when they aren't diskless (see https://github.com/axboe/fio/blob/master/filesetup.c#L1237 ) so hence the preference for an option...

2021-02-14 20:13 UTC, sitsofe requested changes
I'd like to see this as an option...

2021-02-15 14:16 UTC, aclamk commented
@sitsofe:
So I will turn it into an option.

2021-04-10 17:45 UTC, sitsofe approved these changes
@aclamk Apologies for the long delay and thank you for your patience.

LGTM!

2021-04-10 17:45 UTC, sitsofe commented
@axboe can this one be pulled?

2021-04-10 17:46 UTC, merged