rpma: add librpma_apm_* and librpma_gpspm_* engines
axboe/fio pull request #1186
Opened 2021-02-11 16:29 UTC by janekmi

The Remote Persistent Memory Access (RPMA) Library is a C library to simplify accessing persistent memory on remote hosts over Remote Direct Memory Access (RDMA).

The librpma_apm_client and librpma_apm_server is a pair of engines which allows benchmarking persistent writes achieved via
the Appliance Persistency Method (APM; natively supported by the librpma library) and regular reads (a part of the RDMA standard).

The librpma_gpspm_client and librpma_gpspm_server is a pair of engines which allows benchmarking persistent writes achieved via the General Purpose Persistency Method (GPSPM; build on top of the librpma API).

The full history of the development of the librpma fio engines is available at: https://github.com/pmem/fio/tree/rpma

Co-Authored-By: Lukasz Dorau <lukasz.dorau@intel.com>
Co-Authored-By: Tomasz Gromadzki <tomasz.gromadzki@intel.com>
Co-Authored-By: Jan Michalski <jan.m.michalski@intel.com>
Co-Authored-By: Oksana Salyk <oksana.salyk@intel.com>

2021-02-14 20:51 UTC, sitsofe requested changes
Phew, this one is big! Some general comments but nothing to severe. @axboe given the sheer number of files should these engines go into a subdirectory?

2021-02-14 20:51 UTC, sitsofe commented on ci/travis-install-librpma.sh
> +git clone https://github.com/pmem/rpma.git
Maybe grab the tarball like you do below? I guess technically I prefer to see curl used even if it needs more parameters :-)

2021-02-14 20:51 UTC, sitsofe commented on ci/travis-install.sh
> +		ci/travis-install-librpma.sh
I wonder if these could just be functions?

2021-02-14 20:51 UTC, sitsofe commented on configure
> +if test "$disable_rdma" != "yes" && compile_prog "" "-lrpma" "rpma"; then
Where is this set? Do you need to add a flag further up? Further, we can probably do this all with `$librpma` by inverting the test to `if test "$librpma" != "no" ;` etc.

2021-02-14 20:51 UTC, sitsofe commented on configure
> +fi
As above

2021-02-14 20:51 UTC, sitsofe commented on engines/librpma_apm.c
> +		struct io_u *first_io_u, struct io_u *last_io_u,
I think the house style is tending towards line up with bracket

2021-02-14 20:51 UTC, sitsofe commented on engines/librpma_apm.c
> +		log_err("Not supported mode.\n");
I'd set `td_verror` like in engines/ime.c. Maybe return `-EINVAL`?

2021-02-14 20:51 UTC, sitsofe commented on engines/librpma_apm.c
> +					"Fio librpma engine will not work until the Direct Write to PMem on the server side is possible (direct_write_to_pmem)\n");
Could you split thi line?

```
log_err("initial text"
             "more text"
             "etc\n")

2021-02-14 20:51 UTC, sitsofe commented on engines/librpma_apm.c
> +			"Remember that flushing to DRAM does not make your data persistent and may be used only for experimental purposes.\n");
Can you wrap this as above.

2021-02-14 20:51 UTC, sitsofe commented on engines/librpma_apm.c
> +		/* XXX log_info mixes with the JSON output */
That's a more generic issue (see https://github.com/axboe/fio/issues/731 ) so I don't think you need to comment it here.

2021-02-14 20:51 UTC, sitsofe commented on engines/librpma_apm.c
> +		/* non fatal error - continue */
Maybe move the comment one line up.

2021-02-14 20:51 UTC, sitsofe commented on engines/librpma_gpspm_flush.pb-c.c
> + * Copyright 2020, Intel Corporation
Technically 2021?

2021-02-14 20:51 UTC, sitsofe commented on engines/librpma_fio.h
> +#define LIBRPMA_FIO_CEIL(a, b) (((a) + (b) - 1) / (b))
What's wrong with`ceil()`? Too slow?

2021-02-14 20:51 UTC, sitsofe commented on engines/librpma_fio.h
> +/* ceil(a / b) = (a + b - 1) / b */
I think you don't need this comment as it literally describes the macro!

2021-02-14 20:51 UTC, sitsofe commented on engines/librpma_fio.h
> +	/* server ip */
Maybe skip the obvious comments that just re-describe what the code says code (but keep the non-obvious ones).

2021-02-14 20:51 UTC, sitsofe commented on engines/librpma_fio.h
> +		unsigned int *io_u_index);
@axboe how do you feel about this typedef?

2021-02-14 20:51 UTC, sitsofe commented on engines/librpma_gpspm.c
> +	}
Above suggestions in a different file apply here too:
- Skip non obvious comments
- Try and wrap to line up with the brackets
- Skip obvious comments but keep the non-obvious comments

2021-02-14 20:51 UTC, sitsofe commented on fio.1
> +.TP
You'll need to document this in the HOWTO too.

2021-02-15 10:10 UTC, ldorau reviewed
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-02-16 08:04 UTC, janekmi reviewed
> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @janekmi and @sitsofe)

___
*[ci/travis-install.sh, line 54 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WQ-r1-54:-MTdmROE5PUbhs5Ign34:b-wp6y3) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/ci/travis-install.sh#L54)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

I wonder if these could just be functions?
</blockquote></details>

I think it is handier to have them as scripts since they can be easily used to set up your own environment not only for setting up ci.
___
*[engines/librpma_apm.c, line 22 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WS-r1-22:-MTdo2E25mk-NMoGqfcz:b654zy7) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/engines/librpma_apm.c#L22)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

I think the house style is tending towards line up with bracket
</blockquote></details>

Can you please write exactly how you imagine adjusting this very line, so I can use it as an example for adjusting others?
___
*[engines/librpma_apm.c, line 110 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WS-r1-110:-MTdopeKEmNBVvisbJwh:bgx27ub) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/engines/librpma_apm.c#L110)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

Could you split thi line?

```
log_err("initial text"
             "more text"
             "etc\n")
</blockquote></details>

I like to have string literals in a single line so it is easier to find in the codebase. Otherwise, you have to guess if and where it may have been got split.
___
*[engines/librpma_apm.c, line 134 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WS-r1-134:-MTdpUOfBFH7srb10NFF:ba2epup) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/engines/librpma_apm.c#L134)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

That's a more generic issue (see https://github.com/axboe/fio/issues/731 ) so I don't think you need to comment it here.
</blockquote></details>

Having an issue is great. I can refer to it here. But I would argue you won't look for issues when you browse through the source code of an engine and you find out something nonintuitive is going on. This is where this comment proves helpful.
___
*[engines/librpma_apm.c, line 137 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WS-r1-137:-MTdpwkx7JezrQipEn3q:bgx27ub) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/engines/librpma_apm.c#L137)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

Can you wrap this as above.
</blockquote></details>

I like to have string literals in a single line so it is easier to find in the codebase. Otherwise, you have to guess if and where it may have been got split.
___
*[engines/librpma_apm.c, line 142 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WS-r1-142:-MTdq5lq7Tw69BB2CU9V:b17erzp) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/engines/librpma_apm.c#L142)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

Maybe move the comment one line up.
</blockquote></details>

This comment is here instead of some kind of an exit/error one would expect. Having it above the logging call would suggest it describes the logging call which it does not.


<!-- Sent from Reviewable.io -->

2021-02-16 08:14 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @janekmi and @sitsofe)

___
*[configure, line 939 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WR-r1-939:-MTdsncC5QsM_LiKBN66:bfu95i3) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/configure#L939)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

Where is this set? Do you need to add a flag further up? Further, we can probably do this all with `$librpma` by inverting the test to `if test "$librpma" != "no" ;` etc.
</blockquote></details>

`$disable_rdma` is set here: https://github.com/janekmi/fio/blob/add-librpma-engines/configure#L205
___
*[configure, line 948 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WR-r1-948:-MTdtJJY8u8P2I5xEhky:b-vh8szk) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/configure#L948)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

As above
</blockquote></details>

I do not follow how you would prefer to change these conditions. Can you write exactly your idea, please?


<!-- Sent from Reviewable.io -->

2021-02-16 08:29 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe, @janekmi, and @sitsofe)

___
*[ci/travis-install-librpma.sh, line 9 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WO-r1-9:-MTdvOqz1vzIrmhpjScQ:b-t37jav) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/ci/travis-install-librpma.sh#L9)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

Maybe grab the tarball like you do below? I guess technically I prefer to see curl used even if it needs more parameters :-)
</blockquote></details>

There is no tarball containing the required commit yet.


<!-- Sent from Reviewable.io -->

2021-02-16 08:58 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe, @janekmi, and @sitsofe)

___
*[engines/librpma_fio.h, line 29 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WU-r1-29:-MTe2p9z6mtHvw5nAQ4q:b-xfhz6p) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/engines/librpma_fio.h#L29)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

I think you don't need this comment as it literally describes the macro!
</blockquote></details>

Not exactly. It also describes the role of the parameters.
___
*[engines/librpma_gpspm_flush.pb-c.c, line 2 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WW-r1-2:-MTdtswb5ioSdxUfEAku:b6tdfkn) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/engines/librpma_gpspm_flush.pb-c.c#L2)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

Technically 2021?
</blockquote></details>

Yeah... we have started the development last year and this particular file hasn't changed since 2020.


<!-- Sent from Reviewable.io -->

2021-02-16 09:07 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe, @janekmi, and @sitsofe)

___
*[engines/librpma_gpspm.c, line 82 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WV-r1-82:-MTe4SlL0GjTkqSn0yTd:bds359i) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/engines/librpma_gpspm.c#L82)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

Above suggestions in a different file apply here too:
- Skip non obvious comments
- Try and wrap to line up with the brackets
- Skip obvious comments but keep the non-obvious comments
</blockquote></details>

1. I have browsed the code one more time. No obvious comments in this particular file have been found. Please, point them out exactly so we can discuss them one-by-one.
2. I have asked for an example in one of your previous comments. I will be happy to do this once we agree on what is to be done.
3. :-)


<!-- Sent from Reviewable.io -->

2021-02-16 09:09 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe, @janekmi, and @sitsofe)

___
*[ci/travis-install-librpma.sh, line 9 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WO-r1-9:-MTe5TJQ5z0cfGRHFpUR:b-housix) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/ci/travis-install-librpma.sh#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is no tarball containing the required commit yet.
</blockquote></details>

I guess we can still download a zip as follows: https://github.com/pmem/rpma/archive/fbac593917e98f3f26abf14f4fad5a832b330f5c.zip


<!-- Sent from Reviewable.io -->

2021-02-16 09:17 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: 17 of 20 files reviewed, 17 unresolved discussions (waiting on @axboe, @janekmi, @ldorau, and @sitsofe)

___
*[engines/librpma_apm.c, line 39 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WS-r1-39:-MTe71KkC6KgC3kea5GT:b-896fix) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/engines/librpma_apm.c#L39)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

I'd set `td_verror` like in engines/ime.c. Maybe return `-EINVAL`?
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 39 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WU-r1-39:-MTe75dw9gPKfjapEEF5:b-896fix) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/engines/librpma_fio.h#L39)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

Maybe skip the obvious comments that just re-describe what the code says code (but keep the non-obvious ones).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 09:18 UTC, ldorau reviewed
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe, @janekmi, and @sitsofe)



<!-- Sent from Reviewable.io -->

2021-02-16 10:20 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe, @janekmi, and @sitsofe)

___
*[ci/travis-install-librpma.sh, line 9 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WO-r1-9:-MTeLdeyAzH07J7WZ_zR:b-bnj460) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/ci/travis-install-librpma.sh#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I guess we can still download a zip as follows: https://github.com/pmem/rpma/archive/fbac593917e98f3f26abf14f4fad5a832b330f5c.zip
</blockquote></details>

Like that? https://github.com/pmem/fio/pull/209/files


<!-- Sent from Reviewable.io -->

2021-02-16 10:53 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe, @janekmi, and @sitsofe)

___
*[engines/librpma_fio.h, line 30 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WU-r1-30:-MTeSvIs2qoYj6x8ChjW:bjytkln) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/engines/librpma_fio.h#L30)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

What's wrong with`ceil()`? Too slow?
</blockquote></details>

I don't like casting integers to doubles and back to integers for something which can be done easily with integers.


<!-- Sent from Reviewable.io -->

2021-02-16 11:03 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe, @janekmi, and @sitsofe)

___
*[ci/travis-install-librpma.sh, line 9 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecnTZXofGuGR0WO-r1-9:-MTeVR9T1GKCqCT9pAAA:b-896fix) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/ci/travis-install-librpma.sh#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Like that? https://github.com/pmem/fio/pull/209/files
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 11:04 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe, @janekmi, and @sitsofe)



<!-- Sent from Reviewable.io -->

2021-02-16 11:10 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe, @janekmi, and @sitsofe)



<!-- Sent from Reviewable.io -->

2021-02-16 11:10 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe and @sitsofe)

___
*[fio.1, line 1966 at r1](https://reviewable.io/reviews/axboe/fio/1186#-MTHsecosg3IPqXsuzz1-r1-1966:-MTeX4reAE7ZJRN70uib:b-896fix) ([raw file](https://github.com/axboe/fio/blob/061b6f34439257bb3b656c21ecf838d6180a51cd/fio.1#L1966)):*
<details><summary><i>Previously, sitsofe (Sitsofe Wheeler) wrote…</i></summary><blockquote>

You'll need to document this in the HOWTO too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 13:54 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe and @sitsofe)



<!-- Sent from Reviewable.io -->

2021-02-26 12:35 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe and @sitsofe)



<!-- Sent from Reviewable.io -->

2021-03-12 11:04 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe and @sitsofe)



<!-- Sent from Reviewable.io -->

2021-03-12 13:56 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/axboe/fio/1186)* status: all files reviewed, 17 unresolved discussions (waiting on @axboe and @sitsofe)



<!-- Sent from Reviewable.io -->

2021-03-18 14:49 UTC, merged