Fix `filesize` description
axboe/fio pull request #1219
Opened 2021-04-20 11:12 UTC by Nikratio

Setting `size` does not actually limit the total size of files created.

Fixes: axboe#1218

2021-04-20 17:24 UTC, sitsofe requested changes
So I think this behaviour stems from https://github.com/axboe/fio/blob/6202c70d8d5cbdd3fb4bc23b96f691cbd25a327e/filesetup.c#L1216-L1229 . We would have to confirm `f->real_file_size` doesn't shrink but if it doesn't then I think your change is correct. You would also have to update the HOWTO (which has the text duplicated in a different format).

2021-04-20 17:28 UTC, sitsofe commented
@Nikratio overall looks it's the right direction. In addition to comments elsewhere:

- Can you check the code is doing what we now suspect?
- I would argue these commits could be squashed into one and some general header given
- Can you add a prefix to the commit titles (see https://github.com/axboe/fio/commits/e7e536b665bd6a9d3e936e0847dbbb6957101da4/fio.1 for ideas)?
- Can you add your Signed-off-by ?

2021-04-21 07:56 UTC, Nikratio commented
Thanks for the review! I can't justify spending time on understanding the implementation. I just noticed that the command was not behaving as documented and wanted to report this.

I have made the same change to `HOWTO` and added a Signed-Off-By header, prefix, and general description in the top commit. This should indeed be squashed into one - if you like the patch, please merge with "Squash & Rebase" and drop all commit descriptions other than the last one. Feel free to adjust the description as well if I didn't get it quite right.

2021-04-22 08:09 UTC, sitsofe commented
I did a search and it looks like the "filesize limited to size" behaviour was introduced in https://github.com/axboe/fio/commit/9c60ce649d3f976d196709d4399bb7c540ce97b5 but was later removed as part of https://github.com/axboe/fio/commit/7bb48f84ac78cac1f90e3e04d0220d90d6a64a6b#diff-c7128ba06f81c567584dfc2b3d851d0b7124c8c73f52d70be6bc3bce4723b43eL133 (but you'll have to click "Load diff" to see line 133).

@axboe do you know if this was intentional?

2021-06-21 19:35 UTC, bardavid commented on HOWTO
> +        has no effect it all if :option:`io_size` is set explicitly).
Typo: has no effect if :option..

2021-06-22 08:23 UTC, Nikratio commented on HOWTO
> +        has no effect it all if :option:`io_size` is set explicitly).
Fixed, thanks.

2021-06-22 12:53 UTC, sitsofe approved these changes
LGTM - @axboe can you pull this one?

2022-01-28 20:51 UTC, vincentkfu commented
This looks good to me. I ran some simple tests and the outcomes were consistent with the relationship among `size`, `filesize`, and `io_size` described here.

`size` by itself sets `io_size` as well as `filesize`:

```
root@ubuntu:~/fio-dev/fio-canonical# ./fio --name=test --size=512K
...
test: Laying out IO file (1 file / 0MiB)
...
  read: IOPS=25.6k, BW=100MiB/s (105MB/s)(512KiB/5msec)
...
Run status group 0 (all jobs):
   READ: bw=100MiB/s (105MB/s), 100MiB/s-100MiB/s (105MB/s-105MB/s), io=512KiB (524kB), run=5-5msec
...
root@ubuntu:~/fio-dev/fio-canonical# ls -l test.0.0
-rw-r--r-- 1 root root 524288 Jan 28 20:39 test.0.0
```


`size` only determines `io_size` when `filesize` is also specified:
```
root@ubuntu:~/fio-dev/fio-canonical# ./fio --name=test --filesize=1M --size=512K
...
test: Laying out IO file (1 file / 1MiB)
...
  read: IOPS=21.3k, BW=83.3MiB/s (87.4MB/s)(512KiB/6msec)

...
   READ: bw=83.3MiB/s (87.4MB/s), 83.3MiB/s-83.3MiB/s (87.4MB/s-87.4MB/s), io=512KiB (524kB), run=6-6msec
root@ubuntu:~/fio-dev/fio-canonical# ls -l test.0.0
-rw-r--r-- 1 root root 1048576 Jan 28 20:39 test.0.0
```


`size` is ignored when both `filesize` and `io_size` are specified:
```
root@ubuntu:~/fio-dev/fio-canonical# ./fio --name=test --filesize=1M --size=512K --io_size=1M
...
  read: IOPS=32.0k, BW=125MiB/s (131MB/s)(1024KiB/8msec)
...
Run status group 0 (all jobs):
   READ: bw=125MiB/s (131MB/s), 125MiB/s-125MiB/s (131MB/s-131MB/s), io=1024KiB (1049kB), run=8-8msec
root@ubuntu:~/fio-dev/fio-canonical# ls -l test.0.0
-rw-r--r-- 1 root root 1048576 Jan 28 20:39 test.0.0
```

2022-01-28 21:51 UTC, merged