Remove librpma engine as librpma library is no longer maintained
axboe/fio pull request #1811
Opened 2024-08-29 12:18 UTC by grom72

Remove librpma engines as the librpma library project has been archived on GitHub.
 

Please confirm that your commit message(s) follow these guidelines:

1. First line is a commit title, a descriptive one-liner for the change
2. Empty second line
3. Commit message body that explains why the change is useful. Break lines that
   aren't something like a URL at 72-74 chars.
4. Empty line
5. Signed-off-by: Real Name <real@email.com>

Reminders:

1. If you modify struct thread_options, also make corresponding changes in
   cconv.c and bump FIO_SERVER_VER in server.h
2. If you change the ioengine interface (hooks, flags, etc), remember to bump
   FIO_IOOPS_VERSION in ioengines.h.

2024-08-29 14:24 UTC, janekmi requested changes

2024-08-29 14:24 UTC, janekmi commented on ci/actions-install.sh
> +                libpmemblk-dev
Restoring `libpmemblk-dev` here seems unnecessary.

2024-08-29 14:24 UTC, janekmi commented on fio.1
> +.BI (rdma)port
It seems this bit: `\fR=\fPint` still makes sense. Please consider keeping it.

2024-08-29 14:46 UTC, janekmi approved these changes

2024-08-29 14:46 UTC, janekmi commented on ci/actions-install.sh
> +                libpmemblk-dev
✅

2024-08-29 14:46 UTC, janekmi commented on fio.1
> +.BI (rdma)port
✅

2024-08-30 21:20 UTC, vincentkfu commented
I have looked through this and see no issues, but we are having a long weekend in the US, so I will wait until Tuesday to merge.

2024-09-03 18:50 UTC, merged